/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica5.ventanas.cantante;

import ec.edu.ups.practica5.controlador.ControladorCantante;
import ec.edu.ups.practica5.dao.CantanteDAO;
import ec.edu.ups.practica5.modelo.Cantante;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Usuario
 */
public class VentanaAgregarCantante extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaAgregarCantante
     */
    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;

    public VentanaAgregarCantante(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jlNombre.setText(mensajes.getString("lbl.nombre"));
        jlApellido.setText(mensajes.getString("lbl.apellido"));
        jlCodigo.setText(mensajes.getString("lbl.codigo"));
        jlEdad.setText(mensajes.getString("lbl.edad"));
        jlSalario.setText(mensajes.getString("lbl.salario"));
        jlNacionalidad.setText(mensajes.getString("lbl.nacionalidad"));
        jlNombreArtistico.setText(mensajes.getString("lbl.nombreArtistico"));
        jlGeneroMusical.setText(mensajes.getString("lbl.generoMusical"));
        jlNumeroSencillos.setText(mensajes.getString("lbl.nSencillos"));
        jlNumeroConciertos.setText(mensajes.getString("lbl.nConciertos"));
        jlNumeroGiras.setText(mensajes.getString("lbl.nGiras"));
        btnAceptar.setText(mensajes.getString("btn.aceptar"));
        btnCancelar.setText(mensajes.getString("btn.Cancelar"));
        String borderTitle = mensajes.getString("jpanel.crearCantante");
        Border border = BorderFactory.createTitledBorder(borderTitle);
        jPanel1.setBorder(border);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNombreCantanteCrear = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jlCodigo = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlEdad = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNacionalidad = new javax.swing.JLabel();
        jlSalario = new javax.swing.JLabel();
        txtCodigoCantanteCrear = new javax.swing.JTextField();
        txtApellidoCantanteCrear = new javax.swing.JTextField();
        txtEdadCantanteCrear = new javax.swing.JTextField();
        txtSalarioCantanteCrear = new javax.swing.JTextField();
        jlNombreArtistico = new javax.swing.JLabel();
        jlGeneroMusical = new javax.swing.JLabel();
        jlNumeroSencillos = new javax.swing.JLabel();
        jlNumeroConciertos = new javax.swing.JLabel();
        jlNumeroGiras = new javax.swing.JLabel();
        txtNombreArtisticoCantanteCrear = new javax.swing.JTextField();
        txtGeneroMusicalCantanteCrear = new javax.swing.JTextField();
        txtSencillosCantanteCrear = new javax.swing.JTextField();
        txtConciertosCantanteCrear = new javax.swing.JTextField();
        txtGirasCantanteCrear = new javax.swing.JTextField();
        cbxNacionalidades = new javax.swing.JComboBox<>();

        jLabel6.setText("Numero de Composiciones");

        jLabel8.setText("Numero de Composiciones");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agregar Cantante");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Cantante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        txtNombreCantanteCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombreCantanteCrear.setToolTipText("Ingrese el nombre del cantante");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jlCodigo.setText("Código");

        jlNombre.setText("Nombre");

        jlEdad.setText("Edad");

        jlApellido.setText("Apellido");

        jlNacionalidad.setText("Nacionalidad");

        jlSalario.setText("Salario");

        txtCodigoCantanteCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodigoCantanteCrear.setToolTipText("Ingrese el código del cantante");

        txtApellidoCantanteCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtApellidoCantanteCrear.setToolTipText("Ingrese el apellido del cantante");

        txtEdadCantanteCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEdadCantanteCrear.setToolTipText("Ingrese la edad del cantante");

        txtSalarioCantanteCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSalarioCantanteCrear.setToolTipText("Ingrese el salario del cantante");

        jlNombreArtistico.setText("Nombre Artístico");

        jlGeneroMusical.setText("Genero Musical");

        jlNumeroSencillos.setText("Número de sencillos");

        jlNumeroConciertos.setText("Número de conciertos");

        jlNumeroGiras.setText("Número de giras");

        txtNombreArtisticoCantanteCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombreArtisticoCantanteCrear.setToolTipText("Ingrese el nombre artistico del cantante");

        txtGeneroMusicalCantanteCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGeneroMusicalCantanteCrear.setToolTipText("Ingrese el género musical del cantante");

        txtSencillosCantanteCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSencillosCantanteCrear.setToolTipText("Ingrese cuántos sencillos tiene el cantante");

        txtConciertosCantanteCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtConciertosCantanteCrear.setToolTipText("Ingrese el n[umeor de conciertos del cantante");

        txtGirasCantanteCrear.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGirasCantanteCrear.setToolTipText("Ingrese el n[umero de giras el cantante");

        cbxNacionalidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione un pais---" }));
        cbxNacionalidades.setToolTipText("");
        cbxNacionalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNacionalidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodigo)
                            .addComponent(jlNombre)
                            .addComponent(jlApellido)
                            .addComponent(jlEdad)
                            .addComponent(jlNacionalidad)
                            .addComponent(jlSalario))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSalarioCantanteCrear)
                            .addComponent(txtEdadCantanteCrear)
                            .addComponent(txtApellidoCantanteCrear)
                            .addComponent(txtNombreCantanteCrear)
                            .addComponent(txtCodigoCantanteCrear)
                            .addComponent(cbxNacionalidades, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNombreArtistico)
                            .addComponent(jlGeneroMusical)
                            .addComponent(jlNumeroSencillos)
                            .addComponent(jlNumeroConciertos)
                            .addComponent(jlNumeroGiras))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreArtisticoCantanteCrear)
                            .addComponent(txtGeneroMusicalCantanteCrear)
                            .addComponent(txtSencillosCantanteCrear)
                            .addComponent(txtConciertosCantanteCrear)
                            .addComponent(txtGirasCantanteCrear))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoCantanteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCantanteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoCantanteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadCantanteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNacionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarioCantanteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreArtisticoCantanteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGeneroMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeneroMusicalCantanteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroSencillos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSencillosCantanteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConciertosCantanteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroGiras, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGirasCantanteCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.setVisible(false);


    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtCodigoCantanteCrear.getText());
        String nombre = txtNombreCantanteCrear.getText();
        String apellido = txtApellidoCantanteCrear.getText();
        int edad = Integer.parseInt(txtEdadCantanteCrear.getText());
        String nacionalidad = (String) cbxNacionalidades.getSelectedItem();
        double salario = Double.parseDouble(txtSalarioCantanteCrear.getText());
        String nombreArtistico = txtNombreArtisticoCantanteCrear.getText();
        String generoMusical = txtGeneroMusicalCantanteCrear.getText();
        int numeroDeSencillos = Integer.parseInt(txtSencillosCantanteCrear.getText());
        int numeroDeConciertos = Integer.parseInt(txtConciertosCantanteCrear.getText());
        int numeroDeGiras = Integer.parseInt(txtGirasCantanteCrear.getText());

        Cantante cantante = new Cantante();

        cantante.setCodigo(codigo);
        cantante.setNombre(nombre);
        cantante.setApellido(apellido);
        cantante.setEdad(edad);

        cantante.setSalario(salario);
        cantante.setNombreArtistico(nombreArtistico);
        cantante.setGeneroMusical(generoMusical);
        cantante.setNumeroDeSencillos(numeroDeSencillos);
        cantante.setNumeroDeConciertos(numeroDeConciertos);
        cantante.setNumeroDeGiras(numeroDeGiras);

        controladorCantante.crearCantante(cantante);

        JOptionPane.showMessageDialog(this, "Cantante agregado exitosamente.");
        this.limpiarCampos();


    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        this.limpiarCampos();
    }//GEN-LAST:event_formInternalFrameClosing

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        String rutaNacionalidades = "src\\main\\resources\\nacionalidades\\paises.csv";
        cargarDatosExcel(rutaNacionalidades, cbxNacionalidades, Locale.getDefault().getLanguage());


    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened

    private void cbxNacionalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNacionalidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNacionalidadesActionPerformed

    private void cargarDatosExcel(String rutaNacionalidades, JComboBox<String> comboBox, String idioma) {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        try {
            BufferedReader br = new BufferedReader(new FileReader(rutaNacionalidades));
            String read;
            while ((read = br.readLine()) != null) {
                String[] valores = read.replaceAll("\"", "").split(",");
                if (valores.length > 0) {
                    String valor;
                    if (idioma.equals("en")) {
                        valor = valores[0]; // Columna para idioma ingles
                    } else if (idioma.equals("es")) {
                        valor = valores[1]; // Columna para idioma español
                    } else {
                        valor = valores[2]; // Columna para idioma frances
                    }
                    model.addElement(valor);
                }
            }
            br.close();
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Error General");
        }
        comboBox.setModel(model);
    }

    public void limpiarCampos() {
        txtCodigoCantanteCrear.setText("");
        txtNombreCantanteCrear.setText("");
        txtApellidoCantanteCrear.setText("");
        txtEdadCantanteCrear.setText("");
        txtSalarioCantanteCrear.setText("");
        txtNombreArtisticoCantanteCrear.setText("");
        txtGeneroMusicalCantanteCrear.setText("");
        txtSencillosCantanteCrear.setText("");
        txtConciertosCantanteCrear.setText("");
        txtGirasCantanteCrear.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbxNacionalidades;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlEdad;
    private javax.swing.JLabel jlGeneroMusical;
    private javax.swing.JLabel jlNacionalidad;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNombreArtistico;
    private javax.swing.JLabel jlNumeroConciertos;
    private javax.swing.JLabel jlNumeroGiras;
    private javax.swing.JLabel jlNumeroSencillos;
    private javax.swing.JLabel jlSalario;
    private javax.swing.JTextField txtApellidoCantanteCrear;
    private javax.swing.JTextField txtCodigoCantanteCrear;
    private javax.swing.JTextField txtConciertosCantanteCrear;
    private javax.swing.JTextField txtEdadCantanteCrear;
    private javax.swing.JTextField txtGeneroMusicalCantanteCrear;
    private javax.swing.JTextField txtGirasCantanteCrear;
    private javax.swing.JTextField txtNombreArtisticoCantanteCrear;
    private javax.swing.JTextField txtNombreCantanteCrear;
    private javax.swing.JTextField txtSalarioCantanteCrear;
    private javax.swing.JTextField txtSencillosCantanteCrear;
    // End of variables declaration//GEN-END:variables
}
