/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica5.ventanas.cantante;

import ec.edu.ups.practica5.controlador.ControladorCantante;
import ec.edu.ups.practica5.modelo.Cantante;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Usuario
 */
public class VentanaActualizarCantante extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaActualizarCompositor
     */
    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;

    public VentanaActualizarCantante(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jlNombre.setText(mensajes.getString("lbl.nombre"));
        jlApellido.setText(mensajes.getString("lbl.apellido"));
        jlCodigo.setText(mensajes.getString("lbl.codigo"));
        jlEdad.setText(mensajes.getString("lbl.edad"));
        jlSalario.setText(mensajes.getString("lbl.salario"));
        jlNacionalidad.setText(mensajes.getString("lbl.nacionalidad"));
        jlNombreArtistico.setText(mensajes.getString("lbl.nombreArtistico"));
        jlGeneroMusical.setText(mensajes.getString("lbl.generoMusical"));
        jlNumeroSencillos.setText(mensajes.getString("lbl.nSencillos"));
        jlNumeroConciertos.setText(mensajes.getString("lbl.nConciertos"));
        jlNumeroGiras.setText(mensajes.getString("lbl.nGiras"));
        btnAceptar.setText(mensajes.getString("btn.aceptar"));
        btnCancelar.setText(mensajes.getString("btn.Cancelar"));
        String borderTitle = mensajes.getString("jpanel.crearCantante");
        Border border = BorderFactory.createTitledBorder(borderTitle);
        jPanel1.setBorder(border);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jlCodigo = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlEdad = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNacionalidad = new javax.swing.JLabel();
        jlSalario = new javax.swing.JLabel();
        jlNombreArtistico = new javax.swing.JLabel();
        jlGeneroMusical = new javax.swing.JLabel();
        jlNumeroSencillos = new javax.swing.JLabel();
        jlNumeroConciertos = new javax.swing.JLabel();
        jlNumeroGiras = new javax.swing.JLabel();
        txtCodigoCantanteActualizar = new javax.swing.JTextField();
        txtNombreCantanteActualizar = new javax.swing.JTextField();
        txtApellidoCantanteActualizar = new javax.swing.JTextField();
        txtEdadCantanteActualizar = new javax.swing.JTextField();
        txtSalarioCantanteActualizar = new javax.swing.JTextField();
        txtNombreArtisticoCantanteActualizar = new javax.swing.JTextField();
        txtGeneroMusicalCantanteActualizar = new javax.swing.JTextField();
        txtSencillosCantanteActualizar = new javax.swing.JTextField();
        txtConciertosCantanteActualizar = new javax.swing.JTextField();
        txtGirasCantanteActualizar = new javax.swing.JTextField();
        btnBuscarCantante = new javax.swing.JButton();
        cbxNacionalidades = new javax.swing.JComboBox<>();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizar Cantante");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actualizar Cantante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jlCodigo.setText("Código");

        jlNombre.setText("Nombre");

        jlEdad.setText("Edad");

        jlApellido.setText("Apellido");

        jlNacionalidad.setText("Nacionalidad");

        jlSalario.setText("Salario");

        jlNombreArtistico.setText("Nombre Artístico");

        jlGeneroMusical.setText("Genero Musical");

        jlNumeroSencillos.setText("Número de sencillos");

        jlNumeroConciertos.setText("Número de conciertos");

        jlNumeroGiras.setText("Número de giras");

        txtCodigoCantanteActualizar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtNombreCantanteActualizar.setEditable(false);
        txtNombreCantanteActualizar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtApellidoCantanteActualizar.setEditable(false);
        txtApellidoCantanteActualizar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtEdadCantanteActualizar.setEditable(false);
        txtEdadCantanteActualizar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtSalarioCantanteActualizar.setEditable(false);
        txtSalarioCantanteActualizar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtNombreArtisticoCantanteActualizar.setEditable(false);
        txtNombreArtisticoCantanteActualizar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtGeneroMusicalCantanteActualizar.setEditable(false);
        txtGeneroMusicalCantanteActualizar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtSencillosCantanteActualizar.setEditable(false);
        txtSencillosCantanteActualizar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtConciertosCantanteActualizar.setEditable(false);
        txtConciertosCantanteActualizar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtGirasCantanteActualizar.setEditable(false);
        txtGirasCantanteActualizar.setToolTipText("Ingrese las cancionesTop100Billboard");

        btnBuscarCantante.setText("Buscar");
        btnBuscarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCantanteActionPerformed(evt);
            }
        });

        cbxNacionalidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione un pais---" }));
        cbxNacionalidades.setToolTipText("");
        cbxNacionalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNacionalidadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodigo)
                            .addComponent(jlNombre)
                            .addComponent(jlApellido)
                            .addComponent(jlEdad)
                            .addComponent(jlNacionalidad)
                            .addComponent(jlSalario)
                            .addComponent(jlNombreArtistico)
                            .addComponent(jlGeneroMusical)
                            .addComponent(jlNumeroSencillos)
                            .addComponent(jlNumeroConciertos)
                            .addComponent(jlNumeroGiras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtConciertosCantanteActualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSencillosCantanteActualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGeneroMusicalCantanteActualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreArtisticoCantanteActualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalarioCantanteActualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoCantanteActualizar)
                            .addComponent(txtNombreCantanteActualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoCantanteActualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEdadCantanteActualizar, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxNacionalidades, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGirasCantanteActualizar))
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarCantante)
                        .addGap(14, 14, 14))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoCantanteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarCantante)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCantanteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoCantanteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadCantanteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNacionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarioCantanteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreArtisticoCantanteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGeneroMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeneroMusicalCantanteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroSencillos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSencillosCantanteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConciertosCantanteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroGiras, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGirasCantanteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCantanteActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.valueOf(txtCodigoCantanteActualizar.getText());
        Cantante cantante = controladorCantante.verCantante(codigo);
        if (cantante != null) {
            txtCodigoCantanteActualizar.setEditable(false);

            txtNombreCantanteActualizar.setText(cantante.getNombre());
            txtNombreCantanteActualizar.setEditable(true);

            txtApellidoCantanteActualizar.setText(cantante.getApellido());
            txtApellidoCantanteActualizar.setEditable(true);

            txtEdadCantanteActualizar.setText(String.valueOf(cantante.getEdad()));
            txtEdadCantanteActualizar.setEditable(true);

            txtSalarioCantanteActualizar.setText(String.valueOf(cantante.getSalario()));
            txtSalarioCantanteActualizar.setEditable(true);

            txtNombreArtisticoCantanteActualizar.setText(cantante.getNombreArtistico());
            txtNombreArtisticoCantanteActualizar.setEditable(true);

            txtGeneroMusicalCantanteActualizar.setText(cantante.getGeneroMusical());
            txtGeneroMusicalCantanteActualizar.setEditable(true);

            txtSencillosCantanteActualizar.setText(String.valueOf(cantante.getNumeroDeSencillos()));
            txtSencillosCantanteActualizar.setEditable(true);

            txtConciertosCantanteActualizar.setText(String.valueOf(cantante.getNumeroDeConciertos()));
            txtConciertosCantanteActualizar.setEditable(true);

            txtGirasCantanteActualizar.setText(String.valueOf(cantante.getNumeroDeGiras()));
            txtGirasCantanteActualizar.setEditable(true);

        } else {
            JOptionPane.showMessageDialog(this, "El cantante ingresado no existe");
        }
    }//GEN-LAST:event_btnBuscarCantanteActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.valueOf(txtCodigoCantanteActualizar.getText());
        String nombre = txtNombreCantanteActualizar.getText();
        String apellido = txtApellidoCantanteActualizar.getText();
        int edad = Integer.parseInt(txtEdadCantanteActualizar.getText());
        String nacionalidad = (String) cbxNacionalidades.getSelectedItem();
        double salario = Double.parseDouble(txtSalarioCantanteActualizar.getText());
        String nombreArtistico = txtNombreArtisticoCantanteActualizar.getText();
        String generoMusical = txtGeneroMusicalCantanteActualizar.getText();
        int numeroDeSencillos = Integer.parseInt(txtSencillosCantanteActualizar.getText());
        int numeroDeConciertos = Integer.parseInt(txtConciertosCantanteActualizar.getText());
        int numeroDeGiras = Integer.parseInt(txtGirasCantanteActualizar.getText());

        Cantante cantante = new Cantante();

        cantante.setCodigo(codigo);
        cantante.setNombre(nombre);
        cantante.setApellido(apellido);
        cantante.setEdad(edad);
        cantante.setNacionalidad(nacionalidad);
        cantante.setSalario(salario);
        cantante.setNombreArtistico(nombreArtistico);
        cantante.setGeneroMusical(generoMusical);
        cantante.setNumeroDeSencillos(numeroDeSencillos);
        cantante.setNumeroDeConciertos(numeroDeConciertos);
        cantante.setNumeroDeGiras(numeroDeGiras);

        if (controladorCantante.actualizarCantante(cantante)) {
            JOptionPane.showMessageDialog(this, "El cantante ha sido actualizado exitosamente! ");
            this.limpiarCampos();
            this.cambiarEstadoCampos(false);
        } else {
            JOptionPane.showMessageDialog(this, "El cantante no ha sido actualizado! ");
        }


    }//GEN-LAST:event_btnAceptarActionPerformed

    private void cbxNacionalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNacionalidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxNacionalidadesActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        String rutaNacionalidades = "src\\main\\resources\\nacionalidades\\paises.csv";
        cargarDatosExcel(rutaNacionalidades, cbxNacionalidades, Locale.getDefault().getLanguage());

    }//GEN-LAST:event_formInternalFrameActivated

    public void limpiarCampos() {
        txtCodigoCantanteActualizar.setText("");
        txtNombreCantanteActualizar.setText("");
        txtApellidoCantanteActualizar.setText("");
        txtEdadCantanteActualizar.setText("");

        txtSalarioCantanteActualizar.setText("");
        txtNombreArtisticoCantanteActualizar.setText("");
        txtGeneroMusicalCantanteActualizar.setText("");
        txtSencillosCantanteActualizar.setText("");
        txtConciertosCantanteActualizar.setText("");
        txtGirasCantanteActualizar.setText("");

    }

    private void cargarDatosExcel(String rutaNacionalidades, JComboBox<String> comboBox, String idioma) {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        try {
            BufferedReader br = new BufferedReader(new FileReader(rutaNacionalidades));
            String read;
            while ((read = br.readLine()) != null) {
                String[] valores = read.replaceAll("\"", "").split(",");
                if (valores.length > 0) {
                    String valor;
                    if (idioma.equals("en")) {
                        valor = valores[0]; // Columna para idioma ingles
                    } else if (idioma.equals("es")) {
                        valor = valores[1]; // Columna para idioma español
                    } else {
                        valor = valores[2]; // Columna para idioma frances
                    }
                    model.addElement(valor);
                }
            }
            br.close();
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Error General");
        }
        comboBox.setModel(model);
    }

    private void cambiarEstadoCampos(boolean estado) {
        this.txtCodigoCantanteActualizar.setEnabled(!estado);
        this.txtNombreCantanteActualizar.setEnabled(estado);
        this.txtApellidoCantanteActualizar.setEnabled(estado);
        this.txtEdadCantanteActualizar.setEnabled(estado);
        this.txtSalarioCantanteActualizar.setEnabled(estado);
        this.txtNombreArtisticoCantanteActualizar.setEnabled(estado);
        this.txtGeneroMusicalCantanteActualizar.setEnabled(estado);
        this.txtSencillosCantanteActualizar.setEnabled(estado);
        this.txtConciertosCantanteActualizar.setEnabled(estado);
        this.txtGirasCantanteActualizar.setEnabled(estado);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscarCantante;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbxNacionalidades;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlEdad;
    private javax.swing.JLabel jlGeneroMusical;
    private javax.swing.JLabel jlNacionalidad;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNombreArtistico;
    private javax.swing.JLabel jlNumeroConciertos;
    private javax.swing.JLabel jlNumeroGiras;
    private javax.swing.JLabel jlNumeroSencillos;
    private javax.swing.JLabel jlSalario;
    private javax.swing.JTextField txtApellidoCantanteActualizar;
    private javax.swing.JTextField txtCodigoCantanteActualizar;
    private javax.swing.JTextField txtConciertosCantanteActualizar;
    private javax.swing.JTextField txtEdadCantanteActualizar;
    private javax.swing.JTextField txtGeneroMusicalCantanteActualizar;
    private javax.swing.JTextField txtGirasCantanteActualizar;
    private javax.swing.JTextField txtNombreArtisticoCantanteActualizar;
    private javax.swing.JTextField txtNombreCantanteActualizar;
    private javax.swing.JTextField txtSalarioCantanteActualizar;
    private javax.swing.JTextField txtSencillosCantanteActualizar;
    // End of variables declaration//GEN-END:variables
}
