/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica5.ventanas.cantante;

import ec.edu.ups.practica5.controlador.ControladorCantante;
import ec.edu.ups.practica5.modelo.Cantante;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class VentanaListarCantantes extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaListarCompositor
     */
    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;

    public VentanaListarCantantes(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        String borderTitle = mensajes.getString("jpanel.listCant");
        Border border = BorderFactory.createTitledBorder(borderTitle);
        DefaultTableModel model = (DefaultTableModel) tblCantantes.getModel();
        String codigo = mensajes.getString("lbl.codigo");
        String nombre = mensajes.getString("lbl.nombre");
        String apellido = mensajes.getString("lbl.codigo");
        String edad = mensajes.getString("lbl.edad");
        String nacionalidad = mensajes.getString("lbl.nacionalidad");
        String salario = mensajes.getString("lbl.salario");
        String nombreArtistico = mensajes.getString("lbl.nombreArtistico");
        String generoMusical = mensajes.getString("lbl.generoMusical");
        String numeroDeSencillos = mensajes.getString("lbl.nSencillos");
        String numeroDeConciertos = mensajes.getString("lbl.nConciertos");
        String numeroDeGiras = mensajes.getString("lbl.nGiras");
        model.setColumnIdentifiers(new String[]{codigo, nombre, apellido, edad, nacionalidad, salario,
            nombreArtistico, generoMusical});
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCantantes = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Listar Cantantes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblCantantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Edad", "Nacionalidad", "Salario", "Nombre Artístico", "Género Musical"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCantantes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        this.cargarDatosTabla();
    }//GEN-LAST:event_formInternalFrameActivated

    private void cargarDatosTabla() {
        DefaultTableModel modelo = (DefaultTableModel) this.tblCantantes.getModel();
        modelo.setNumRows(0);
        List<Cantante> listaDeCantantes = controladorCantante.verCantantes();
        for (Cantante cantante : listaDeCantantes) {
            int codigo = cantante.getCodigo();
            String nombre = cantante.getNombre();
            Object[] rowData = {codigo, nombre};
            modelo.addRow(rowData);
        }
        this.tblCantantes.setModel(modelo);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCantantes;
    // End of variables declaration//GEN-END:variables
}
