/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica5.ventanas.cantante;

import ec.edu.ups.practica5.controlador.ControladorCantante;
import ec.edu.ups.practica5.modelo.Cantante;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author Usuario
 */
public class VentanaEliminarCantante extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaEliminarCompositor
     */
    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;
    
    public VentanaEliminarCantante(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jlNombre.setText(mensajes.getString("lbl.nombre"));
        jlApellido.setText(mensajes.getString("lbl.apellido"));
        jlCodigo.setText(mensajes.getString("lbl.codigo"));
        jlEdad.setText(mensajes.getString("lbl.edad"));
        jlSalario.setText(mensajes.getString("lbl.salario"));
        jlNacionalidad.setText(mensajes.getString("lbl.nacionalidad"));
        jlNombreArtistico.setText(mensajes.getString("lbl.nombreArtistico"));
        jlGeneroMusical.setText(mensajes.getString("lbl.generoMusical"));
        jlNumeroSencillos.setText(mensajes.getString("lbl.nSencillos"));
        jlNumeroConciertos.setText(mensajes.getString("lbl.nConciertos"));
        jlNumeroGiras.setText(mensajes.getString("lbl.nGiras"));
        btnAceptar.setText(mensajes.getString("btn.aceptar"));
        btnCancelar.setText(mensajes.getString("btn.Cancelar"));
        String borderTitle = mensajes.getString("jpanel.crearCantante");
        Border border = BorderFactory.createTitledBorder(borderTitle);
        jPanel1.setBorder(border);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jlCodigo = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlEdad = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNacionalidad = new javax.swing.JLabel();
        jlSalario = new javax.swing.JLabel();
        jlNombreArtistico = new javax.swing.JLabel();
        jlGeneroMusical = new javax.swing.JLabel();
        jlNumeroSencillos = new javax.swing.JLabel();
        jlNumeroConciertos = new javax.swing.JLabel();
        jlNumeroGiras = new javax.swing.JLabel();
        txtCodigoCantanteEliminar = new javax.swing.JTextField();
        txtNombreCantanteEliminar = new javax.swing.JTextField();
        txtApellidoCantanteEliminar = new javax.swing.JTextField();
        txtEdadCantanteEliminar = new javax.swing.JTextField();
        txtNacionalidadCantanteEliminar = new javax.swing.JTextField();
        txtSalarioCantanteEliminar = new javax.swing.JTextField();
        txtNombreArtisticoCantanteEliminar = new javax.swing.JTextField();
        txtGeneroMusicalCantanteEliminar = new javax.swing.JTextField();
        txtSencillosCantanteEliminar = new javax.swing.JTextField();
        txtConciertosCantanteEliminar = new javax.swing.JTextField();
        txtGirasCantanteEliminar = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar Cantante");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar Cantante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        btnAceptar.setText("Buscar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jlCodigo.setText("Código");

        jlNombre.setText("Nombre");

        jlEdad.setText("Edad");

        jlApellido.setText("Apellido");

        jlNacionalidad.setText("Nacionalidad");

        jlSalario.setText("Salario");

        jlNombreArtistico.setText("Nombre Artístico");

        jlGeneroMusical.setText("Genero Musical");

        jlNumeroSencillos.setText("Número de sencillos");

        jlNumeroConciertos.setText("Número de conciertos");

        jlNumeroGiras.setText("Número de giras");

        txtCodigoCantanteEliminar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtNombreCantanteEliminar.setEditable(false);
        txtNombreCantanteEliminar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtApellidoCantanteEliminar.setEditable(false);
        txtApellidoCantanteEliminar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtEdadCantanteEliminar.setEditable(false);
        txtEdadCantanteEliminar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtNacionalidadCantanteEliminar.setEditable(false);
        txtNacionalidadCantanteEliminar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtSalarioCantanteEliminar.setEditable(false);
        txtSalarioCantanteEliminar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtNombreArtisticoCantanteEliminar.setEditable(false);
        txtNombreArtisticoCantanteEliminar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtGeneroMusicalCantanteEliminar.setEditable(false);
        txtGeneroMusicalCantanteEliminar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtSencillosCantanteEliminar.setEditable(false);
        txtSencillosCantanteEliminar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtConciertosCantanteEliminar.setEditable(false);
        txtConciertosCantanteEliminar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtGirasCantanteEliminar.setEditable(false);
        txtGirasCantanteEliminar.setToolTipText("Ingrese las cancionesTop100Billboard");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEliminar)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlCodigo)
                        .addComponent(jlNombre)
                        .addComponent(jlApellido)
                        .addComponent(jlEdad)
                        .addComponent(jlNacionalidad)
                        .addComponent(jlSalario)
                        .addComponent(jlNombreArtistico)
                        .addComponent(jlGeneroMusical)
                        .addComponent(jlNumeroSencillos)
                        .addComponent(jlNumeroConciertos)
                        .addComponent(jlNumeroGiras)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdadCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNacionalidadCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalarioCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreArtisticoCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSencillosCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConciertosCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGirasCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGeneroMusicalCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCodigoCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAceptar)))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNacionalidadCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarioCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreArtisticoCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGeneroMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeneroMusicalCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlNumeroSencillos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSencillosCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlNumeroConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtConciertosCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroGiras, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGirasCantanteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnCancelar))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.valueOf(txtCodigoCantanteEliminar.getText());
        Cantante cantante = controladorCantante.verCantante(codigo);
        if (cantante != null) {
            txtCodigoCantanteEliminar.setEditable(false);
            txtNombreCantanteEliminar.setText(cantante.getNombre());
            txtApellidoCantanteEliminar.setText(cantante.getApellido());
            txtEdadCantanteEliminar.setText(String.valueOf(cantante.getEdad()));
            txtNacionalidadCantanteEliminar.setText(cantante.getNacionalidad());
            txtSalarioCantanteEliminar.setText(String.valueOf(cantante.getSalario()));
            txtNombreArtisticoCantanteEliminar.setText(cantante.getNombreArtistico());
            txtGeneroMusicalCantanteEliminar.setText(cantante.getGeneroMusical());
            txtSencillosCantanteEliminar.setText(String.valueOf(cantante.getNumeroDeSencillos()));
            txtConciertosCantanteEliminar.setText(String.valueOf(cantante.getNumeroDeConciertos()));
            txtGirasCantanteEliminar.setText(String.valueOf(cantante.getNumeroDeGiras()));
            
        } else {
            JOptionPane.showMessageDialog(this, "El cantante ingresado no existe");
        }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.valueOf(txtCodigoCantanteEliminar.getText());
        
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Estas seguro que deseas eliminar al cantante?");
        if (respuesta == JOptionPane.YES_OPTION) {
            if (controladorCantante.eliminarCantante(codigo)) {
                JOptionPane.showMessageDialog(this, "El cantante ha sido eliminada exitosamente!");
                this.limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar al cantante!");
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    public void limpiarCampos() {
        txtCodigoCantanteEliminar.setText("");
        txtNombreCantanteEliminar.setText("");
        txtApellidoCantanteEliminar.setText("");
        txtEdadCantanteEliminar.setText("");
        txtNacionalidadCantanteEliminar.setText("");
        txtSalarioCantanteEliminar.setText("");
        txtNombreArtisticoCantanteEliminar.setText("");
        txtGeneroMusicalCantanteEliminar.setText("");
        txtSencillosCantanteEliminar.setText("");
        txtConciertosCantanteEliminar.setText("");
        txtGirasCantanteEliminar.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlEdad;
    private javax.swing.JLabel jlGeneroMusical;
    private javax.swing.JLabel jlNacionalidad;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNombreArtistico;
    private javax.swing.JLabel jlNumeroConciertos;
    private javax.swing.JLabel jlNumeroGiras;
    private javax.swing.JLabel jlNumeroSencillos;
    private javax.swing.JLabel jlSalario;
    private javax.swing.JTextField txtApellidoCantanteEliminar;
    private javax.swing.JTextField txtCodigoCantanteEliminar;
    private javax.swing.JTextField txtConciertosCantanteEliminar;
    private javax.swing.JTextField txtEdadCantanteEliminar;
    private javax.swing.JTextField txtGeneroMusicalCantanteEliminar;
    private javax.swing.JTextField txtGirasCantanteEliminar;
    private javax.swing.JTextField txtNacionalidadCantanteEliminar;
    private javax.swing.JTextField txtNombreArtisticoCantanteEliminar;
    private javax.swing.JTextField txtNombreCantanteEliminar;
    private javax.swing.JTextField txtSalarioCantanteEliminar;
    private javax.swing.JTextField txtSencillosCantanteEliminar;
    // End of variables declaration//GEN-END:variables
}
