/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica5.ventanas.cantante;

import ec.edu.ups.practica5.controlador.ControladorCantante;
import ec.edu.ups.practica5.modelo.Cantante;
import ec.edu.ups.practica5.modelo.Disco;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Usuario
 */
public class VentanaBuscarCantante extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaBuscarCompositor
     */
    private ControladorCantante controladorCantante;
    private ResourceBundle mensajes;

    public VentanaBuscarCantante(ControladorCantante controladorCantante) {
        initComponents();
        this.controladorCantante = controladorCantante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jlNombre.setText(mensajes.getString("lbl.nombre"));
        jlApellido.setText(mensajes.getString("lbl.apellido"));
        jlCodigo.setText(mensajes.getString("lbl.codigo"));
        jlEdad.setText(mensajes.getString("lbl.edad"));
        jlSalario.setText(mensajes.getString("lbl.salario"));
        jlNacionalidad.setText(mensajes.getString("lbl.nacionalidad"));
        jlNombreArtistico.setText(mensajes.getString("lbl.nombreArtistico"));
        jlGeneroMusical.setText(mensajes.getString("lbl.generoMusical"));
        jlNumeroSencillos.setText(mensajes.getString("lbl.nSencillos"));
        jlNumeroConciertos.setText(mensajes.getString("lbl.nConciertos"));
        jlNumeroGiras.setText(mensajes.getString("lbl.nGiras"));
        btnAceptar.setText(mensajes.getString("btn.aceptar"));
        btnCancelar.setText(mensajes.getString("btn.Cancelar"));
        String borderTitle = mensajes.getString("jpanel.crearCantante");
        Border border = BorderFactory.createTitledBorder(borderTitle);
        jPanel4.setBorder(border);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        jlCodigo = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlEdad = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlNacionalidad = new javax.swing.JLabel();
        jlSalario = new javax.swing.JLabel();
        jlNombreArtistico = new javax.swing.JLabel();
        jlGeneroMusical = new javax.swing.JLabel();
        jlNumeroSencillos = new javax.swing.JLabel();
        jlNumeroConciertos = new javax.swing.JLabel();
        jlNumeroGiras = new javax.swing.JLabel();
        txtCodigoCantanteBuscar = new javax.swing.JTextField();
        txtNombreCantanteBuscar = new javax.swing.JTextField();
        txtApellidoCantanteBuscar = new javax.swing.JTextField();
        txtEdadCantanteBuscar = new javax.swing.JTextField();
        txtNacionalidadCantanteBuscar = new javax.swing.JTextField();
        txtSalarioCantanteBuscar = new javax.swing.JTextField();
        txtNombreArtisticoCantanteBuscar = new javax.swing.JTextField();
        txtGeneroMusicalCantanteBuscar = new javax.swing.JTextField();
        txtSencillosCantanteBuscar = new javax.swing.JTextField();
        txtConciertosCantanteBuscar = new javax.swing.JTextField();
        txtGirasCantanteBuscar = new javax.swing.JTextField();
        btnBuscarCantante = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOperadoras = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Cantante");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Cantante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(153, 153, 153));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jlCodigo.setText("Código");

        jlNombre.setText("Nombre");

        jlEdad.setText("Edad");

        jlApellido.setText("Apellido");

        jlNacionalidad.setText("Nacionalidad");

        jlSalario.setText("Salario");

        jlNombreArtistico.setText("Nombre Artístico");

        jlGeneroMusical.setText("Genero Musical");

        jlNumeroSencillos.setText("Número de sencillos");

        jlNumeroConciertos.setText("Número de conciertos");

        jlNumeroGiras.setText("Número de giras");

        txtCodigoCantanteBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodigoCantanteBuscar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtNombreCantanteBuscar.setEditable(false);
        txtNombreCantanteBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombreCantanteBuscar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtApellidoCantanteBuscar.setEditable(false);
        txtApellidoCantanteBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtApellidoCantanteBuscar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtEdadCantanteBuscar.setEditable(false);
        txtEdadCantanteBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEdadCantanteBuscar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtNacionalidadCantanteBuscar.setEditable(false);
        txtNacionalidadCantanteBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNacionalidadCantanteBuscar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtSalarioCantanteBuscar.setEditable(false);
        txtSalarioCantanteBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSalarioCantanteBuscar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtNombreArtisticoCantanteBuscar.setEditable(false);
        txtNombreArtisticoCantanteBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombreArtisticoCantanteBuscar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtGeneroMusicalCantanteBuscar.setEditable(false);
        txtGeneroMusicalCantanteBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGeneroMusicalCantanteBuscar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtSencillosCantanteBuscar.setEditable(false);
        txtSencillosCantanteBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSencillosCantanteBuscar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtConciertosCantanteBuscar.setEditable(false);
        txtConciertosCantanteBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtConciertosCantanteBuscar.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtGirasCantanteBuscar.setEditable(false);
        txtGirasCantanteBuscar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtGirasCantanteBuscar.setToolTipText("Ingrese las cancionesTop100Billboard");

        btnBuscarCantante.setText("Buscar");
        btnBuscarCantante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCantanteActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        tblOperadoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOperadoras);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jlCodigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCodigoCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNombre)
                            .addComponent(jlApellido)
                            .addComponent(jlEdad)
                            .addComponent(jlNacionalidad)
                            .addComponent(jlSalario)
                            .addComponent(jlNombreArtistico)
                            .addComponent(jlGeneroMusical)
                            .addComponent(jlNumeroSencillos)
                            .addComponent(jlNumeroConciertos)
                            .addComponent(jlNumeroGiras))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGirasCantanteBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConciertosCantanteBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSencillosCantanteBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGeneroMusicalCantanteBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreArtisticoCantanteBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalarioCantanteBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNacionalidadCantanteBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCantanteBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoCantanteBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdadCantanteBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnBuscarCantante)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnAceptar)
                        .addGap(53, 53, 53)
                        .addComponent(btnCancelar)
                        .addContainerGap(226, Short.MAX_VALUE))))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCantante))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNacionalidadCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarioCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreArtistico, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreArtisticoCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlGeneroMusical, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGeneroMusicalCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroSencillos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSencillosCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroConciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConciertosCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroGiras, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGirasCantanteBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();

    }//GEN-LAST:event_btnAceptarActionPerformed
    private void cargarDiscos(Cantante cantante) {
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel) this.tblOperadoras.getModel();
        modelo.removeAllElements();

        List<Disco> listaDiscos = cantante.listarDiscos();
        if (!listaDiscos.isEmpty()) {
            for (Disco disco : listaDiscos) {
                modelo.addElement(disco.getNombre());
            }
        } else {
            modelo.addElement("No tiene discos");
        }
    }
    private void btnBuscarCantanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCantanteActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.valueOf(txtCodigoCantanteBuscar.getText());
        Cantante cantante = controladorCantante.verCantante(codigo);
        if (cantante != null) {
            txtCodigoCantanteBuscar.setEditable(false);
            txtNombreCantanteBuscar.setText(cantante.getNombre());
            txtApellidoCantanteBuscar.setText(cantante.getApellido());
            txtEdadCantanteBuscar.setText(String.valueOf(cantante.getEdad()));
            txtNacionalidadCantanteBuscar.setText(cantante.getNacionalidad());
            txtSalarioCantanteBuscar.setText(String.valueOf(cantante.calcularSalario()));
            txtNombreArtisticoCantanteBuscar.setText(cantante.getNombreArtistico());
            txtGeneroMusicalCantanteBuscar.setText(cantante.getGeneroMusical());
            txtSencillosCantanteBuscar.setText(String.valueOf(cantante.getNumeroDeSencillos()));
            txtConciertosCantanteBuscar.setText(String.valueOf(cantante.getNumeroDeConciertos()));
            txtGirasCantanteBuscar.setText(String.valueOf(cantante.getNumeroDeGiras()));

        } else {
            JOptionPane.showMessageDialog(this, "El cantante ingresado no existe");
        }

    }//GEN-LAST:event_btnBuscarCantanteActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        this.limpiarCampos();
        txtCodigoCantanteBuscar.setEditable(true);
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.setVisible(false);

    }//GEN-LAST:event_btnCancelarActionPerformed

    public void limpiarCampos() {
        txtCodigoCantanteBuscar.setText("");
        txtNombreCantanteBuscar.setText("");
        txtApellidoCantanteBuscar.setText("");
        txtEdadCantanteBuscar.setText("");
        txtNacionalidadCantanteBuscar.setText("");
        txtSalarioCantanteBuscar.setText("");
        txtNombreArtisticoCantanteBuscar.setText("");
        txtGeneroMusicalCantanteBuscar.setText("");
        txtSencillosCantanteBuscar.setText("");
        txtConciertosCantanteBuscar.setText("");
        txtGirasCantanteBuscar.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnBuscarCantante;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlEdad;
    private javax.swing.JLabel jlGeneroMusical;
    private javax.swing.JLabel jlNacionalidad;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNombreArtistico;
    private javax.swing.JLabel jlNumeroConciertos;
    private javax.swing.JLabel jlNumeroGiras;
    private javax.swing.JLabel jlNumeroSencillos;
    private javax.swing.JLabel jlSalario;
    private javax.swing.JTable tblOperadoras;
    private javax.swing.JTextField txtApellidoCantanteBuscar;
    private javax.swing.JTextField txtCodigoCantanteBuscar;
    private javax.swing.JTextField txtConciertosCantanteBuscar;
    private javax.swing.JTextField txtEdadCantanteBuscar;
    private javax.swing.JTextField txtGeneroMusicalCantanteBuscar;
    private javax.swing.JTextField txtGirasCantanteBuscar;
    private javax.swing.JTextField txtNacionalidadCantanteBuscar;
    private javax.swing.JTextField txtNombreArtisticoCantanteBuscar;
    private javax.swing.JTextField txtNombreCantanteBuscar;
    private javax.swing.JTextField txtSalarioCantanteBuscar;
    private javax.swing.JTextField txtSencillosCantanteBuscar;
    // End of variables declaration//GEN-END:variables
}
