/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.practica5.ventanas.compositor;

import ec.edu.ups.practica5.controlador.ControladorCompositor;
import ec.edu.ups.practica5.modelo.Compositor;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaAgregarCompositor extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaAgregarCantante
     */
    private ControladorCompositor controladorCompositor;
    private ResourceBundle mensajes;

    public VentanaAgregarCompositor(ControladorCompositor controladorCompositor) {
        initComponents();
        this.controladorCompositor = controladorCompositor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void cambiarIdioma(Locale localizacion) {
        mensajes = ResourceBundle.getBundle("mensajes.mensaje", localizacion);
        jlNombre.setText(mensajes.getString("lbl.nombre"));
        jlApellido.setText(mensajes.getString("lbl.apellido"));
        jlCodigo.setText(mensajes.getString("lbl.codigo"));
        jlEdad.setText(mensajes.getString("lbl.edad"));
        jlSalario.setText(mensajes.getString("lbl.salario"));
        jlNacionalidad.setText(mensajes.getString("lbl.nacionalidad"));
        jlNumeroComposiciones.setText(mensajes.getString("lbl.nComposiciones"));
        btnAceptar.setText(mensajes.getString("btn.aceptar"));
        btnCancelar.setText(mensajes.getString("btn.Cancelar"));

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNombre = new javax.swing.JLabel();
        txtEdadCompositor = new javax.swing.JTextField();
        jlEdad = new javax.swing.JLabel();
        txtSalarioCompositor = new javax.swing.JTextField();
        txtNombreCompositor = new javax.swing.JTextField();
        jlApellido = new javax.swing.JLabel();
        jlNacionalidad = new javax.swing.JLabel();
        jlSalario = new javax.swing.JLabel();
        txtCodigoCompositor = new javax.swing.JTextField();
        jlCodigo = new javax.swing.JLabel();
        txtApellidoCompositor = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jlNumeroComposiciones = new javax.swing.JLabel();
        txtComposicionesCompositor = new javax.swing.JTextField();
        cbxNacionalidades = new javax.swing.JComboBox<>();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("AgregarCompositor");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jlNombre.setText("Nombre");

        txtEdadCompositor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtEdadCompositor.setToolTipText("Ingrese las cancionesTop100Billboard");

        jlEdad.setText("Edad");

        txtSalarioCompositor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSalarioCompositor.setToolTipText("Ingrese las cancionesTop100Billboard");

        txtNombreCompositor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNombreCompositor.setToolTipText("Ingrese las cancionesTop100Billboard");

        jlApellido.setText("Apellido");

        jlNacionalidad.setText("Nacionalidad");

        jlSalario.setText("Salario");

        txtCodigoCompositor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodigoCompositor.setToolTipText("Ingrese las cancionesTop100Billboard");

        jlCodigo.setText("Código");

        txtApellidoCompositor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtApellidoCompositor.setToolTipText("Ingrese las cancionesTop100Billboard");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jlNumeroComposiciones.setText("Número de composiciones");

        txtComposicionesCompositor.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtComposicionesCompositor.setToolTipText("Ingrese las cancionesTop100Billboard");

        cbxNacionalidades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione un pais---" }));
        cbxNacionalidades.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodigo)
                            .addComponent(jlNombre)
                            .addComponent(jlApellido)
                            .addComponent(jlEdad)
                            .addComponent(jlNacionalidad)
                            .addComponent(jlSalario)
                            .addComponent(jlNumeroComposiciones))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComposicionesCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSalarioCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdadCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigoCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxNacionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnAceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEdadCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNacionalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalarioCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNumeroComposiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComposicionesCompositor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.limpiarCampos();
        this.setVisible(false);

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:

        int codigo = Integer.valueOf(txtCodigoCompositor.getText());
        String nombre = txtNombreCompositor.getText();
        String apellido = txtApellidoCompositor.getText();
        int edad = Integer.valueOf(txtEdadCompositor.getText());
        String nacionalidad = (String) cbxNacionalidades.getSelectedItem();
        double salario = Double.valueOf(txtSalarioCompositor.getText());
        int numeroDeComposiciones = Integer.valueOf(txtComposicionesCompositor.getText());

        Compositor compositor = new Compositor();

        compositor.setCodigo(codigo);
        compositor.setNombre(nombre);
        compositor.setApellido(apellido);
        compositor.setEdad(edad);
        compositor.setNacionalidad(nacionalidad);
        compositor.setSalario(salario);
        compositor.setNumeroDeComposiciones(numeroDeComposiciones);

        controladorCompositor.crearCompositor(compositor);

        JOptionPane.showMessageDialog(this, "Compositor agregado correctamente.");


    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        String rutaNacionalidades = "src\\main\\resources\\nacionalidades\\paises.csv";
        cargarDatosExcel(rutaNacionalidades, cbxNacionalidades, Locale.getDefault().getLanguage());
    }//GEN-LAST:event_formInternalFrameActivated

    public void limpiarCampos() {
        txtCodigoCompositor.setText("");
        txtNombreCompositor.setText("");
        txtApellidoCompositor.setText("");
        txtEdadCompositor.setText("");
        txtSalarioCompositor.setText("");
        txtComposicionesCompositor.setText("");

    }

    private void cargarDatosExcel(String rutaNacionalidades, JComboBox<String> comboBox, String idioma) {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();

        try {
            BufferedReader br = new BufferedReader(new FileReader(rutaNacionalidades));
            String read;
            while ((read = br.readLine()) != null) {
                String[] valores = read.replaceAll("\"", "").split(",");
                if (valores.length > 0) {
                    String valor;
                    if (idioma.equals("en")) {
                        valor = valores[0]; // Columna para idioma ingles
                    } else if (idioma.equals("es")) {
                        valor = valores[1]; // Columna para idioma español
                    } else {
                        valor = valores[2]; // Columna para idioma frances
                    }
                    model.addElement(valor);
                }
            }
            br.close();
        } catch (Exception e) {
            e.printStackTrace();
            System.err.println("Error General");
        }
        comboBox.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbxNacionalidades;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlEdad;
    private javax.swing.JLabel jlNacionalidad;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNumeroComposiciones;
    private javax.swing.JLabel jlSalario;
    private javax.swing.JTextField txtApellidoCompositor;
    private javax.swing.JTextField txtCodigoCompositor;
    private javax.swing.JTextField txtComposicionesCompositor;
    private javax.swing.JTextField txtEdadCompositor;
    private javax.swing.JTextField txtNombreCompositor;
    private javax.swing.JTextField txtSalarioCompositor;
    // End of variables declaration//GEN-END:variables

}
